# Debug Data Msg

geometry_msgs/Point[]      ref_pos
geometry_msgs/Quaternion[] ref_att
geometry_msgs/Vector3[]    ref_vel
geometry_msgs/Vector3[]    ref_body_rate
geometry_msgs/Vector3[]    ref_torque
geometry_msgs/Vector3[]    ref_att_degree
float64[] ref_thrust
std_msgs/Float64MultiArray output_thrust_moment
std_msgs/Float64MultiArray INDIadd_thrust_moment
std_msgs/Float64MultiArray output_thrusts
std_msgs/Float64MultiArray output_motor_speed
std_msgs/Float64MultiArray output_dshot